data:
  train_path: "data/train.parquet"
  test_path: "data/test.parquet"
  target: "clicked"
  cat_patterns: ["gender", "age_group", "inventory_id", "l_feat_*", "feat_*"]
  num_patterns: ["day_of_week", "hour", "history_*"]
  min_freq: 10
model:
  type: ft_transformer
  embed_dim: 64
  n_layers: 4
  n_heads: 8
  ff_mult: 4
  dropout: 0.1
  stochastic_depth: 0.1
train:
  batch_size: 131072
  epochs: 10
  lr: 0.0006
  weight_decay: 0.02
  warmup_steps: 4000
  mixed_precision: bf16
  folds: 5
  seed: 42


