data:
  train_path: "data/train.parquet"
  test_path: "data/test.parquet"
  target: "clicked"
  cat_patterns: ["gender", "age_group", "inventory_id", "l_feat_*", "feat_*"]
  num_patterns: ["day_of_week", "hour", "history_*"]
  min_freq: 10
model:
  type: xdeepfm
  embed_dim: 32
  cin_layers: [128, 128]
  dnn_layers: [256, 128, 64]
  dropout: 0.1
train:
  batch_size: 262144
  epochs: 8
  lr: 0.0008
  weight_decay: 0.02
  early_stop_patience: 3
  mixed_precision: bf16
  folds: 5
  seed: 42


