
# Example config for CTR-Maximizer
data_path: /path/to/your/data.parquet   # CSV also works
label_col: label
time_col: time           # optional; if missing we do stratified random split
weight_col: null         # optional sample weights
use_polars: true
valid_frac: 0.1
test_frac: 0.1

# Models
use_xgboost: true
use_catboost: true
use_transformer: true
prefer_gpu: true

xgboost_params:
  max_depth: 8
  eta: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  tree_method: gpu_hist   # for A100

catboost_params:
  depth: 8
  learning_rate: 0.1
  l2_leaf_reg: 3.0
  eval_metric: PRAUC
  iterations: 10000
  od_wait: 300
  random_seed: 42
  verbose: 200
  task_type: GPU
  devices: 0

transformer_params:
  max_epochs: 8
  batch_size: 65536
  lr: 0.0002
  d_model: 128
  nhead: 8
  num_layers: 4
  dim_feedforward: 256
  dropout: 0.1

# Post-processing
calibrate: true
